name: prueba_buffet
description: "App móvil para realizar pedidos rápidos, gestionar pagos y evitar filas en el buffet escolar."
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  dio: ^5.9.2

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  get: ^4.6.6
  get_storage: ^2.1.1
  sn_progress_dialog: ^1.1.4
  url_launcher: ^6.0.20
  local_auth: ^2.3.0
  intl: 0.20.2
  flutter_localization: ^0.3.0
  app_links: ^6.4.1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  connectivity_plus: ^7.0.0
  dio_cookie_manager: ^3.4.0
  cookie_jar: ^4.0.9
  logger: ^2.4.0
  package_info_plus: ^9.0.0
  

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.3


flutter_launcher_icons:
  android: true
  image_path: assets/images/ylogo.png
  web:
    generate: true
    image_path: "assets/images/ylogo.png"
    background_color: "#ffffff" # Opcional, por si tu logo tiene transparencias

flutter_native_splash:
  image: assets/images/ylogo.png
  color: "#ffffff"
  image_dark: assets/images/ylogo.png
  color_dark: "#ffffff"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/categorias/
    - assets/images/intro/
    # - assets/images/categorias/bebidas_categoria.png
    # - assets/images/categorias/snacks_categoria.png
    # - assets/images/categorias/golosinas_categoria.png
    # - assets/images/categorias/galletitas_categoria.png
    # - assets/images/logo-sin.png
    # - assets/images/cart_empty.png
    # - assets/images/intro/img_intro_screen.png
    # - assets/images/pago_efect.png
    # - assets/images/pago_transf.png
    # - assets/images/y_yapaso.png
    # - assets/images/bloqueo.png
    # - assets/images/icono_carga.png
    # - assets/images/icono_trans.png
    # - assets/images/not_load.png
    # - assets/images/order_confirm.png
    # - assets/images/codigo_barra.png
    # - assets/images/Profile.png
    # - assets/images/COMPRA_EXITOSA.png
    # - assets/images/CARGA_SALDO_EXITOSO.png
    # - assets/images/error_pago.png
    # - assets/images/ylogo.png
    # - assets/images/logo-negativo.png
    # - assets/images/mercado_pago.png

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-Regular.ttf

